[package]
name = "dekkonot/sha256"
description = "Implementation of the SHA-256 hashing algorithm"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

version = "1.0.1"

include = ["*.luau", "wally.toml"]
exclude = ["*"]

[dependencies]
